version: "3"

services:
    node-test:
        build: .
        # restart: always
        ports:
            - "8080:8080"
        environment:
            PORT: 8080
            NODE_ENV: production
